server:
 port: 2222
 
eureka:
 instance:
  hostname: peer2
  
 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl: 
   defaultZone: http://peer1:1111/eureka/,http://peer3:3333/eureka/
  
spring:
 application:
  name: my-servers
 redis:
  host: localhost
  port: 6379
  
dx:
 name: name2222