server:
 port: 3333
 
eureka:
 instance:
  hostname: peer3

 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl: 
   defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
  
spring:
 application:
  name: my-servers
 session:
  store-type: redis
 redis:
  host: localhost
  port: 6379

dx:
 name: name3333